language: java
jdk:
  - openjdk17

before_install:
  - wget https://github.com/shyiko/jabba/raw/master/install.sh && chmod +x install.sh
  - ./install.sh
  - jabba install adopt@1.17.0-1

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"
# CI 실행 완료시 메일로 알림
notifications:
  email:
    recipients:
      - devchyun96@naver.com